import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Header from "../components/Header";
import LotteryEntrance from "../components/LotteryEntrance";
import { useMoralis } from "react-moralis";
import WalletIcon from '@mui/icons-material/Wallet';
import LinkOffIcon from '@mui/icons-material/LinkOff';


const supportedChains = ["31337", "11155111"]

export default function Home() {
  const { isWeb3Enabled, chainId } = useMoralis();

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {isWeb3Enabled ? (
          <div>
              {supportedChains.includes(parseInt(chainId).toString()) ? (
                  <div className="flex flex-row justify-center item-center">
                      <LotteryEntrance className="" />
                  </div>
              ) : (

                  <div className={"h-[90vh] flex flex-col justify-center items-center"}>

                      <LinkOffIcon sx={{
                          fontSize: "50px"
                      }} />

                      <div className={'text-center p-2 text-[20px]'}>{`Please switch to a supported chainId. The supported Chain Ids are: ${supportedChains}`}</div>
                  </div>

              )}
          </div>
          )
          :
          (
              <div className={"h-[90vh] flex flex-col justify-center items-center"}>

            <WalletIcon sx={{
                fontSize: "50px"
            }} />
            <p className={"text-[20px]"}>Please connect to a Wallet</p>

        </div>
      )}
    </div>
  );
}
